# Beanstalk Versioning System

# Beanstalk Version
BEANSTALK_VERSION_MAJOR = 4.4
BEANSTALK_VERSION_MINOR = 4.065
BEANSTALK_VERSION_MAINTENANCE =
VERSION := $(BEANSTALK_VERSION_MAJOR).$(BEANSTALK_VERSION_MINOR)$(BEANSTALK_VERSION_MAINTENANCE)

# Set BEANSTALK_BUILDTYPE
ifdef BEANSTALK_NIGHTLY
BEANSTALK_BUILDTYPE := NIGHTLY
endif
ifdef BEANSTALK_EXPERIMENTAL
BEANSTALK_BUILDTYPE := EXPERIMENTAL
endif
ifdef BEANSTALK_RELEASE
BEANSTALK_BUILDTYPE := RELEASE
endif

# Set Unofficial if no buildtype set (Buildtype should ONLY be set by Beanstalk Devs!)
ifdef BEANSTALK_BUILDTYPE
else
BEANSTALK_BUILDTYPE := UNOFFICIAL
BEANSTALK_VERSION_MAJOR := 4.4
BEANSTALK_VERSION_MINOR := 4.065
endif

# Set Beanstalk version
ifdef BEANSTALK_RELEASE
BEANSTALK_VERSION := "BeanStalk-v"$(VERSION)
else
BEANSTALK_VERSION := "$(TARGET_PRODUCT)-$(BEANSTALK_BUILDTYPE)"-$(shell date +%Y%m%d-%H%M)
endif

PRODUCT_PROPERTY_OVERRIDES += \
ro.modversion=$(BEANSTALK_VERSION) \
ro.beanstalk.version=$(VERSION)-$(BEANSTALK_BUILDTYPE)
ro.bs=true \
ro.goo.developerid=beanstalk \
ro.goo.rom=$(BEANSTALK_BUILD) \
ro.goo.version=30
